### ISSUE TITLE
Error using default example

### ISSUE THREAD

**Issue by AppLetico** [cbargren/express-brute-mongoose#16]
TypeError: schema.virtuals[key]._applyDefaultGetters is not a function

**Comment by davidmwhynot** [comment]
I also am having this issue.

**Comment by cbargren** [comment]
Sorry for the delay in getting back to you. I'm not positive, but I'm guessing this is due to an issue with some version mismatches. With the [latest version (v1.1.0)](https://www.npmjs.com/package/express-brute-mongoose/v/1.1.0) that I just released, I'm now just exporting a raw json object from the schema definition and expect you to create the schema to be passed into mongoose yourself. This helps by preventing us from having any version weirdness around mongoose, since you're just using your own mongoose to create the schema.

The important part of those changes look like this:
```javascript
const schema = require('express-brute-mongoose/dist/schema');
// ...
const model = mongoose.model('bruteforce', new mongoose.Schema(schema));
```

If you're still having the issue after updating, reopen this ticket with your mongoose and mongodb version. Thanks!
