### ISSUE TITLE
Update mongoose to the latest version

### ISSUE THREAD

**Issue by darwinbeard** [cbargren/express-brute-mongoose#2]
Mongoose ~4.5.0 doesn't support latest functionality.
Can it be upgraded to 4.9.* ?

**Comment by cbargren** [comment]
Yeah... Realistically, it should be as loose as possible on its restriction for the mongoose version, so that it can match whatever is being used in the parent project whenever possible. I switched it to `*`, which should work for your use case. I've fixed that and published a new version: https://github.com/cbargren/express-brute-mongoose/releases/tag/v0.0.8
